import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Timeline from '@/components/Timeline';
import Marquee from 'react-fast-marquee';

export default function Home() {
  return (
    <>
      <Head>
        <title>Gamsky Football Analysis</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <>
          <Navbar />
          <Marquee
            style={{
              backgroundColor: '#222',
              color: '#f5f5f5',
              padding: '8px',
              fontSize: '32px',
            }}
          >
            <h1>FOOTBALL ANALYSIS</h1>
          </Marquee>
          <Timeline />
        </>
      </main>
    </>
  );
}
